import { useState, useEffect } from "react";
import { useQuery, useMutation, useAction } from "convex/react";
import { api } from "../../convex/_generated/api";
import { getPlayerToken } from "../utils/storage";

interface GameScreenProps {
  roomId: string;
}

export default function GameScreen({ roomId }: GameScreenProps) {
  const [prompt, setPrompt] = useState("");
  const [hasSubmitted, setHasSubmitted] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [judgingInProgress, setJudgingInProgress] = useState(false);

  const playerToken = getPlayerToken();
  // @ts-expect-error - api.games will be generated by Convex
  const room = useQuery(api.games.getRoom, { roomId: roomId as any });
  // @ts-expect-error - api.games will be generated by Convex
  const gameState = useQuery(api.games.getGameState, { roomId: roomId as any });
  // @ts-expect-error - api.games will be generated by Convex
  const scoreboard = useQuery(api.games.getScoreboard, { roomId: roomId as any });
  // @ts-expect-error - api.games will be generated by Convex
  const submitPrompt = useMutation(api.games.submitPrompt);
  // @ts-expect-error - api.games will be generated by Convex
  const judgeRound = useAction(api.games.judgeRound);
  // @ts-expect-error - api.games will be generated by Convex
  const nextRound = useMutation(api.games.nextRound);

  // Check if player has submitted
  useEffect(() => {
    if (gameState && playerToken) {
      const submission = gameState.submissions.find(
        (s) => s.playerId === playerToken
      );
      setHasSubmitted(!!submission);
      if (submission) {
        setPrompt(submission.prompt);
      }
    }
  }, [gameState, playerToken]);

  // Monitor game state changes
  useEffect(() => {
    if (gameState) {
      if (gameState.status === "judging") {
        setJudgingInProgress(true);
        setShowResults(false);
      } else if (gameState.status === "results") {
        setJudgingInProgress(false);
        setShowResults(true);
        // Auto-trigger judging if not already done
        if (!gameState.allJudged && gameState.submissions.length > 0) {
          handleJudgeRound();
        }
      } else if (gameState.status === "prompt") {
        setShowResults(false);
        setJudgingInProgress(false);
        setHasSubmitted(false);
        setPrompt("");
      }
    }
  }, [gameState?.status]);

  const handleSubmitPrompt = async () => {
    if (!prompt.trim()) {
      alert("Please enter a prompt");
      return;
    }

    try {
      await submitPrompt({
        roomId: roomId as any,
        playerToken: playerToken!,
        prompt: prompt.trim(),
      });
      setHasSubmitted(true);
    } catch (err: any) {
      alert(err.message || "Failed to submit prompt");
    }
  };

  const handleJudgeRound = async () => {
    try {
      setJudgingInProgress(true);
      await judgeRound({ roomId: roomId as any });
    } catch (err: any) {
      alert(err.message || "Failed to judge round");
      setJudgingInProgress(false);
    }
  };

  const handleNextRound = async () => {
    try {
      const result = await nextRound({ roomId: roomId as any });
      if (result.finished) {
        // Game ended - could show final screen
        alert("Game finished! Check the scoreboard.");
      }
      setShowResults(false);
    } catch (err: any) {
      alert(err.message || "Failed to start next round");
    }
  };

  if (!gameState || !room) {
    return <div>Loading game...</div>;
  }

  const currentPlayer = room.players.find((p) => p.playerId === playerToken);
  const currentSubmission = gameState.submissions.find(
    (s) => s.playerId === playerToken
  );
  const isHost = playerToken === room.hostId;

  // Check if all players submitted
  const allSubmitted =
    gameState.status === "prompt" &&
    gameState.submissions.length === room.players.length &&
    room.players.length > 0;

  if (room.status === "finished") {
    return (
      <div style={{ maxWidth: "800px", margin: "0 auto", padding: "2rem" }}>
        <h1>Game Finished!</h1>
        <h2>Final Scoreboard</h2>
        <div style={{ marginBottom: "2rem" }}>
          {scoreboard?.map((player, idx) => (
            <div
              key={player.playerId}
              style={{
                padding: "1rem",
                backgroundColor: idx === 0 
                  ? "var(--scoreboard-leader-bg, #fff9e6)" 
                  : "var(--scoreboard-player-bg, #fff)",
                borderRadius: "4px",
                border: "1px solid var(--scoreboard-border, #ddd)",
                marginBottom: "0.5rem",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                color: "var(--scoreboard-text, inherit)",
              }}
            >
              <div>
                <span style={{ fontSize: "1.5rem", marginRight: "1rem" }}>
                  #{idx + 1}
                </span>
                <span style={{ fontSize: "1.2rem", fontWeight: "bold" }}>
                  {player.name}
                </span>
                {idx === 0 && (
                  <span
                    style={{
                      marginLeft: "1rem",
                      fontSize: "0.9rem",
                      color: "#ffa500",
                      fontWeight: "bold",
                    }}
                  >
                    🏆 WINNER
                  </span>
                )}
              </div>
              <span style={{ fontSize: "1.2rem", fontWeight: "bold" }}>
                {player.score} / {room.maxRounds}
              </span>
            </div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "2rem" }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "2rem",
        }}
      >
        <h1>Round {gameState.currentRound} of {room.maxRounds}</h1>
        {currentPlayer && (
          <div>
            <strong>Your Score: {currentPlayer.score}</strong>
          </div>
        )}
      </div>

      {gameState.scenario && (
        <div
          style={{
            backgroundColor: "var(--scenario-bg, #f0f0f0)",
            padding: "2rem",
            borderRadius: "8px",
            marginBottom: "2rem",
          }}
        >
          <h2 style={{ marginTop: 0, color: "var(--scenario-title-color, inherit)" }}>Scenario</h2>
          <p style={{ fontSize: "1.2rem", lineHeight: "1.6", color: "var(--scenario-text-color, inherit)" }}>
            {gameState.scenario.description}
          </p>
        </div>
      )}

      {gameState.status === "prompt" && (
        <div style={{ marginBottom: "2rem" }}>
          <label
            style={{
              display: "block",
              marginBottom: "0.5rem",
              fontWeight: "bold",
              fontSize: "1.1rem",
            }}
          >
            Your Prompt (mention other players with @Name to sabotage!)
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            disabled={hasSubmitted}
            placeholder="Enter your prompt to complete the scenario..."
            style={{
              width: "100%",
              minHeight: "120px",
              padding: "1rem",
              fontSize: "1rem",
              borderRadius: "4px",
              border: "1px solid #ccc",
              fontFamily: "inherit",
              resize: "vertical",
            }}
          />
          <button
            onClick={handleSubmitPrompt}
            disabled={hasSubmitted || !prompt.trim()}
            style={{
              marginTop: "1rem",
              width: "100%",
              padding: "1rem",
              fontSize: "1.1rem",
              fontWeight: "bold",
              backgroundColor: hasSubmitted ? "#4caf50" : "#646cff",
              color: "white",
              border: "none",
              borderRadius: "4px",
              cursor: hasSubmitted ? "not-allowed" : "pointer",
            }}
          >
            {hasSubmitted ? "✓ Submitted" : "Submit Prompt"}
          </button>
          {hasSubmitted && (
            <p style={{ marginTop: "0.5rem", color: "var(--waiting-text-secondary, #666)" }}>
              Waiting for other players to submit...
              {allSubmitted && isHost && (
                <button
                  onClick={handleJudgeRound}
                  style={{
                    marginLeft: "1rem",
                    padding: "0.5rem 1rem",
                    backgroundColor: "#ff9800",
                    color: "white",
                    border: "none",
                    borderRadius: "4px",
                    cursor: "pointer",
                  }}
                >
                  Start Judging
                </button>
              )}
            </p>
          )}
        </div>
      )}

      {(gameState.status === "judging" || judgingInProgress) && (
        <div
          style={{
            padding: "2rem",
            backgroundColor: "var(--judging-bg, #e8f4f8)",
            borderRadius: "8px",
            textAlign: "center",
            color: "var(--judging-text, inherit)",
          }}
        >
          <h2>Judging in progress...</h2>
          <p>AI is evaluating all submissions. This may take a moment.</p>
        </div>
      )}

      {showResults && gameState.status === "results" && (
        <div style={{ marginBottom: "2rem" }}>
          <h2>Round Results</h2>
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            {gameState.submissions
              .sort((a, b) => {
                // Sort by winner first, then by submission time
                if (a.isWinner && !b.isWinner) return -1;
                if (!a.isWinner && b.isWinner) return 1;
                return a.submittedAt - b.submittedAt;
              })
              .map((submission) => (
                <div
                  key={submission._id}
                  style={{
                    padding: "1.5rem",
                    backgroundColor: submission.isWinner 
                      ? "var(--result-winner-bg, #e8f5e9)" 
                      : "var(--result-loser-bg, #ffebee)",
                    borderRadius: "8px",
                    border: `2px solid ${
                      submission.isWinner 
                        ? "var(--result-winner-border, #4caf50)" 
                        : "var(--result-loser-border, #f44336)"
                    }`,
                    color: "var(--result-text, inherit)",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      marginBottom: "1rem",
                    }}
                  >
                    <h3 style={{ margin: 0 }}>
                      {submission.playerName}
                      {submission.playerId === playerToken && " (You)"}
                    </h3>
                    <span
                      style={{
                        padding: "0.5rem 1rem",
                        borderRadius: "4px",
                        backgroundColor: submission.isWinner ? "#4caf50" : "#f44336",
                        color: "white",
                        fontWeight: "bold",
                      }}
                    >
                      {submission.isWinner ? "✓ WINNER" : "✗ LOST"}
                    </span>
                  </div>
                  <div style={{ marginBottom: "1rem" }}>
                    <strong>Prompt:</strong>
                    <p style={{ margin: "0.5rem 0", fontStyle: "italic" }}>
                      "{submission.prompt}"
                    </p>
                  </div>
                  {submission.outcome && (
                    <div>
                      <strong>Outcome:</strong>
                      <p style={{ margin: "0.5rem 0" }}>{submission.outcome}</p>
                    </div>
                  )}
                </div>
              ))}
          </div>

          <div style={{ marginTop: "2rem", marginBottom: "2rem" }}>
            <h2>Current Scoreboard</h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
              {scoreboard?.map((player, idx) => (
                <div
                  key={player.playerId}
                  style={{
                    padding: "1rem",
                    backgroundColor: idx === 0 
                      ? "var(--scoreboard-leader-bg, #fff9e6)" 
                      : "var(--scoreboard-player-bg, #fff)",
                    borderRadius: "4px",
                    border: "1px solid var(--scoreboard-border, #ddd)",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    color: "var(--scoreboard-text, inherit)",
                  }}
                >
                  <div>
                    <span style={{ fontSize: "1.2rem", marginRight: "1rem" }}>
                      #{idx + 1}
                    </span>
                    <span>{player.name}</span>
                    {player.playerId === playerToken && (
                      <span style={{ marginLeft: "0.5rem", color: "var(--scoreboard-you-text, #666)" }}>
                        (You)
                      </span>
                    )}
                  </div>
                  <span style={{ fontSize: "1.2rem", fontWeight: "bold" }}>
                    {player.score}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {isHost && (
            <button
              onClick={handleNextRound}
              style={{
                width: "100%",
                padding: "1rem",
                fontSize: "1.1rem",
                fontWeight: "bold",
                backgroundColor: "#646cff",
                color: "white",
                border: "none",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              {gameState.currentRound >= room.maxRounds
                ? "End Game"
                : "Next Round"}
            </button>
          )}

          {!isHost && (
            <div
              style={{
                padding: "1rem",
                backgroundColor: "var(--waiting-bg, #e8f4f8)",
                borderRadius: "4px",
                textAlign: "center",
                color: "var(--waiting-text, inherit)",
              }}
            >
              Waiting for host to start next round...
            </div>
          )}
        </div>
      )}
    </div>
  );
}

