import { useState, useEffect, useRef } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { 
  setPlayerToken, 
  getPlayerToken, 
  getPlayerName, 
  setPlayerName
} from "../utils/storage";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog";
import { X, Crown, User, Edit2, LogOut, Play, Copy } from "lucide-react";
import type { Id } from "../../convex/_generated/dataModel";

interface LobbyProps {
  onRoomCreated: (roomId: string) => void;
  onRoomJoined: (roomId: string) => void;
  onGameStart: (roomId?: string) => void;
}

export default function Lobby({ onRoomCreated, onRoomJoined, onGameStart }: LobbyProps) {
  const [playerName, setPlayerNameState] = useState("");
  const [gameCode, setGameCode] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [isJoining, setIsJoining] = useState(false);
  const [error, setError] = useState("");
  const [showNameDialog, setShowNameDialog] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const [editingName, setEditingName] = useState("");
  const [editingPlayerId, setEditingPlayerId] = useState<string | null>(null);
  const [currentRoomId, setCurrentRoomId] = useState<Id<"rooms"> | null>(null);
  const hasRedirectedRef = useRef(false);

  // @ts-expect-error - api.games will be generated by Convex
  const createRoom = useMutation(api.games.createRoom);
  // @ts-expect-error - api.games will be generated by Convex
  const joinRoom = useMutation(api.games.joinRoom);
  // @ts-expect-error - api.games will be generated by Convex
  const kickPlayer = useMutation(api.games.kickPlayer);
  // @ts-expect-error - api.games will be generated by Convex
  const leaveRoom = useMutation(api.games.leaveRoom);
  // @ts-expect-error - api.games will be generated by Convex
  const startGame = useMutation(api.games.startGame);
  // @ts-expect-error - api.players will be generated by Convex
  const setPlayerNameMutation = useMutation(api.players.setPlayerName);

  // Check if user has a name on mount
  useEffect(() => {
    const savedName = getPlayerName();
    if (!savedName) {
      setShowNameDialog(true);
    } else {
      setPlayerNameState(savedName);
    }

    // Check if user is in a room
    const token = getPlayerToken();
    if (token) {
      // Try to find if player is in a room by querying
      // This is a simplified approach - in production you might store roomId in localStorage
    }
  }, []);

  // Query for current room - first try explicit roomId, then query by player token
  const playerToken = getPlayerToken();
  // @ts-expect-error - api.games will be generated by Convex
  const roomById = useQuery(
    api.games?.getRoom,
    currentRoomId ? { roomId: currentRoomId } : "skip"
  );
  // @ts-expect-error - api.players will be generated by Convex
  const roomByPlayer = useQuery(
    api.players?.getPlayerRoom,
    playerToken && !currentRoomId ? { playerToken } : "skip"
  );

  const currentRoom = roomById || roomByPlayer;

  // Update currentRoomId when we get room from player query
  useEffect(() => {
    if (roomByPlayer) {
      if (!currentRoomId || currentRoomId !== roomByPlayer._id) {
        setCurrentRoomId(roomByPlayer._id);
        // Notify parent about the room only if it's new
        if (!currentRoomId) {
          onRoomJoined(roomByPlayer._id);
        }
      }
    } else if (!roomByPlayer && currentRoomId) {
      // Player was kicked or removed from room - clear current room
      setCurrentRoomId(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [roomByPlayer?._id]);

  // Check if player is still in the room (in case they were kicked)
  useEffect(() => {
    if (currentRoom && playerToken && currentRoomId) {
      const playerInRoom = currentRoom.players.find(p => p.playerId === playerToken);
      if (!playerInRoom && currentRoomId) {
        // Player was kicked from the room
        setCurrentRoomId(null);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentRoom?.players.length, playerToken]);

  // Auto-redirect to game if it has already started
  useEffect(() => {
    if (
      currentRoom && 
      currentRoomId &&
      (currentRoom.status === "playing" || currentRoom.status === "finished") &&
      currentRoom._id === currentRoomId &&
      !hasRedirectedRef.current
    ) {
      hasRedirectedRef.current = true;
      onGameStart(currentRoom._id);
    }
    // Reset redirect flag when room status changes back to waiting
    if (currentRoom?.status === "waiting") {
      hasRedirectedRef.current = false;
    }
    // Reset redirect flag when roomId changes
    if (!currentRoomId) {
      hasRedirectedRef.current = false;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentRoom?.status, currentRoom?._id]);

  const handleNameSubmit = () => {
    if (!playerName.trim()) {
      setError("Please enter your name");
      return;
    }
    setPlayerName(playerName.trim());
    setShowNameDialog(false);
    setError("");
  };

  const handleEditName = () => {
    const currentName = getPlayerName();
    setEditingName(currentName || "");
    setIsEditingName(true);
  };

  const handleSaveName = async () => {
    if (!editingName.trim()) {
      setError("Please enter your name");
      return;
    }
    
    const trimmedName = editingName.trim();
    setPlayerName(trimmedName);
    setPlayerNameState(trimmedName);
    setIsEditingName(false);
    setError("");

    // Update name in database if player has a token
    const token = getPlayerToken();
    if (token) {
      try {
        await setPlayerNameMutation({
          playerToken: token,
          name: trimmedName,
        });
      } catch (err) {
        // Silently fail - name is saved in localStorage anyway
        console.error("Failed to update player name:", err);
      }
    }
  };

  const handleSavePlayerName = async (playerIdToUpdate: string) => {
    if (!editingName.trim()) {
      setError("Please enter a name");
      return;
    }

    const trimmedName = editingName.trim();
    
    // Only allow editing own name
    if (playerIdToUpdate !== playerToken) {
      setError("You can only edit your own name");
      return;
    }

    // Update localStorage
    setPlayerName(trimmedName);
    setPlayerNameState(trimmedName);
    setEditingPlayerId(null);
    setEditingName("");
    setError("");

    // Update name in database
    if (playerToken) {
      try {
        await setPlayerNameMutation({
          playerToken: playerToken,
          name: trimmedName,
        });
      } catch (err) {
        console.error("Failed to update player name:", err);
        setError("Failed to update name");
      }
    }
  };

  const handleCancelEdit = () => {
    setIsEditingName(false);
    setEditingName("");
    setError("");
  };

  const handleCreateRoom = async () => {
    const name = getPlayerName() || playerName.trim();
    if (!name) {
      setShowNameDialog(true);
      return;
    }

    setIsCreating(true);
    setError("");

    try {
      let token = getPlayerToken();
      if (!token) {
        token = crypto.randomUUID();
        setPlayerToken(token);
      }

      const result = await createRoom({
        hostToken: token,
        playerName: name,
      });

      setCurrentRoomId(result.roomId);
      onRoomCreated(result.roomId);
    } catch (err: any) {
      setError(err.message || "Failed to create room");
    } finally {
      setIsCreating(false);
    }
  };

  const handleJoinRoom = async () => {
    const name = getPlayerName() || playerName.trim();
    if (!name) {
      setShowNameDialog(true);
      return;
    }

    if (!gameCode.trim()) {
      setError("Please enter a game code");
      return;
    }

    setIsJoining(true);
    setError("");

    try {
      let token = getPlayerToken();
      if (!token) {
        token = crypto.randomUUID();
        setPlayerToken(token);
      }

      const result = await joinRoom({
        gameCode: gameCode.trim().toUpperCase(),
        playerToken: token,
        playerName: name,
      });

      setCurrentRoomId(result.roomId);
      onRoomJoined(result.roomId);
    } catch (err: any) {
      setError(err.message || "Failed to join room");
    } finally {
      setIsJoining(false);
    }
  };

  const handleKickPlayer = async (playerIdToKick: string) => {
    if (!currentRoomId) return;

    const token = getPlayerToken();
    if (!token) return;

    try {
      await kickPlayer({
        roomId: currentRoomId,
        hostToken: token,
        playerIdToKick,
      });
    } catch (err: any) {
      setError(err.message || "Failed to kick player");
    }
  };

  const handleLeaveRoom = async () => {
    if (!currentRoomId) return;

    const token = getPlayerToken();
    if (!token) return;

    try {
      await leaveRoom({
        roomId: currentRoomId,
        playerToken: token,
      });
      setCurrentRoomId(null);
      setGameCode("");
    } catch (err: any) {
      setError(err.message || "Failed to leave room");
    }
  };

  const handleStartGame = async () => {
    if (!currentRoomId) return;

    try {
      await startGame({ roomId: currentRoomId });
      onGameStart(currentRoomId);
    } catch (err: any) {
      setError(err.message || "Failed to start game");
    }
  };

  const handleCopyCode = () => {
    if (currentRoom?.gameCode) {
      navigator.clipboard.writeText(currentRoom.gameCode);
      // Could add a toast notification here
    }
  };

  const isHost = currentRoom && playerToken && currentRoom.hostId === playerToken;

  return (
    <>
      <Dialog open={showNameDialog} onOpenChange={setShowNameDialog}>
        <DialogContent className="sm:max-w-[425px] animate-in fade-in-0 zoom-in-95">
          <DialogHeader>
            <DialogTitle>Welcome to AI Game!</DialogTitle>
            <DialogDescription>
              Please enter your name to get started.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Input
                id="name"
                placeholder="Enter your name"
                value={playerName}
                onChange={(e) => setPlayerNameState(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    handleNameSubmit();
                  }
                }}
                autoFocus
                className="animate-in fade-in-0 slide-in-from-top-2"
              />
              {error && (
                <p className="text-sm text-destructive animate-in fade-in-0">
                  {error}
                </p>
              )}
            </div>
          </div>
          <DialogFooter>
            <Button
              onClick={handleNameSubmit}
              disabled={!playerName.trim()}
              className="animate-in fade-in-0 slide-in-from-bottom-2"
            >
              Continue
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <div className="bg-gradient-to-br from-background via-background to-muted/20 p-4 md:p-8 relative overflow-hidden">
        {/* Robot Puppet Background Element */}
        <div className="absolute top-0 right-0 w-96 h-96 md:w-[500px] md:h-[500px] opacity-10 md:opacity-20 pointer-events-none animate-in fade-in-0 duration-1000">
          <img 
            src="/robot_puppet_asset.png" 
            alt="Robot Puppeteer" 
            className="w-full h-full object-contain"
            style={{ transform: 'rotate(-5deg)' }}
          />
        </div>

        {/* Player Name in Top Right Corner */}
        {getPlayerName() && !isEditingName && (
          <div className="absolute top-4 right-4 z-20 animate-in fade-in-0 slide-in-from-right-4">
            <div className="flex items-center gap-2 px-4 py-2 bg-card/80 backdrop-blur-sm border border-border rounded-lg shadow-lg">
              <User className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium text-foreground">
                {getPlayerName()}
              </span>
              <Button
                variant="ghost"
                size="icon"
                onClick={handleEditName}
                className="h-6 w-6 ml-1"
              >
                <Edit2 className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        )}

        {/* Edit Name Input in Top Right Corner */}
        {isEditingName && (
          <div className="absolute top-4 right-4 z-20 animate-in fade-in-0 slide-in-from-right-4">
            <div className="flex items-center gap-2 px-4 py-2 bg-card/80 backdrop-blur-sm border border-border rounded-lg shadow-lg">
              <Input
                value={editingName}
                onChange={(e) => setEditingName(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    handleSaveName();
                  } else if (e.key === "Escape") {
                    handleCancelEdit();
                  }
                }}
                className="h-8 w-32 text-sm"
                autoFocus
                placeholder="Your name"
              />
              <Button
                variant="ghost"
                size="icon"
                onClick={handleSaveName}
                className="h-6 w-6"
                disabled={!editingName.trim()}
              >
                <span className="text-xs">✓</span>
              </Button>
              <Button
                variant="ghost"
                size="icon"
                onClick={handleCancelEdit}
                className="h-6 w-6"
              >
                <X className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>
        )}

        <div className="max-w-7xl mx-auto relative z-10">
          {/* Header */}
          <div className="mb-8 text-center animate-in fade-in-0 slide-in-from-top-4 duration-700">
            <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent mb-2">
              Prompt Puppeteer
            </h1>
            <p className="text-muted-foreground">AI and Convex powered multiplayer prompt battles</p>
          </div>

          <div className="grid md:grid-cols-2 gap-6 lg:gap-8">
            {/* Left Side - Host/Join Actions */}
            <div className="space-y-6 animate-in fade-in-0 slide-in-from-left-4 duration-700">
              <Card className="shadow-lg border-2 hover:shadow-xl transition-shadow duration-300">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <User className="h-5 w-5" />
                    Create Room
                  </CardTitle>
                  <CardDescription>
                    Start a new game and invite friends
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Button
                    onClick={handleCreateRoom}
                    disabled={isCreating || isJoining}
                    className="w-full h-12 text-lg font-semibold hover:scale-[1.02] active:scale-[0.98] transition-transform"
                    size="lg"
                  >
                    {isCreating ? (
                      <span className="flex items-center gap-2">
                        <span className="animate-spin">⏳</span>
                        Creating...
                      </span>
                    ) : (
                      "Host Game"
                    )}
                  </Button>
                </CardContent>
              </Card>

              <Card className="shadow-lg border-2 hover:shadow-xl transition-shadow duration-300">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <User className="h-5 w-5" />
                    Join Room
                  </CardTitle>
                  <CardDescription>
                    Enter a game code to join an existing room
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <Input
                      type="text"
                      value={gameCode}
                      onChange={(e) => setGameCode(e.target.value.toUpperCase())}
                      placeholder="Enter game code"
                      maxLength={6}
                      className="text-center text-2xl font-mono tracking-widest uppercase"
                      onKeyDown={(e) => {
                        if (e.key === "Enter") {
                          handleJoinRoom();
                        }
                      }}
                    />
                  </div>
                  <Button
                    onClick={handleJoinRoom}
                    disabled={isCreating || isJoining || !gameCode.trim()}
                    className="w-full h-12 text-lg font-semibold hover:scale-[1.02] active:scale-[0.98] transition-transform"
                    size="lg"
                    variant="secondary"
                  >
                    {isJoining ? (
                      <span className="flex items-center gap-2">
                        <span className="animate-spin">⏳</span>
                        Joining...
                      </span>
                    ) : (
                      "Join Game"
                    )}
                  </Button>
                </CardContent>
              </Card>

              {error && (
                <Card className="border-destructive bg-destructive/10 animate-in fade-in-0 slide-in-from-bottom-2">
                  <CardContent className="pt-6">
                    <p className="text-destructive font-medium">{error}</p>
                  </CardContent>
                </Card>
              )}
            </div>

            {/* Right Side - Current Lobby */}
            <div className="animate-in fade-in-0 slide-in-from-right-4 duration-700">
              <Card className="shadow-lg border-2 h-full">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <User className="h-5 w-5" />
                    Current Lobby
                  </CardTitle>
                  <CardDescription>
                    {currentRoom
                      ? `Room: ${currentRoom.gameCode}`
                      : "No active room"}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {currentRoom ? (
                    <div className="space-y-4">
                      {/* Game Code with Copy Button */}
                      <div className="bg-muted/50 p-4 rounded-lg border-2 border-dashed relative">
                        <div className="text-xs text-muted-foreground mb-1">
                          Share this code:
                        </div>
                        <div className="flex items-center justify-between gap-2">
                          <div className="text-3xl font-mono font-bold text-primary tracking-widest">
                            {currentRoom.gameCode}
                          </div>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={handleCopyCode}
                            className="h-8 w-8"
                            title="Copy code"
                          >
                            <Copy className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>

                      {/* Players List */}
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <h3 className="font-semibold text-sm text-muted-foreground">
                            Players ({currentRoom.players.length}/6)
                          </h3>
                          {currentRoom.players.length >= 6 && (
                            <span className="text-xs font-semibold text-orange-600 dark:text-orange-400 bg-orange-100 dark:bg-orange-900/30 px-2 py-1 rounded-full">
                              Room Full
                            </span>
                          )}
                        </div>
                        <div className="space-y-2 max-h-64 overflow-y-auto">
                          {currentRoom.players.map((player, index) => {
                            const isCurrentPlayer = player.playerId === playerToken;
                            const isEditingThisPlayer = editingPlayerId === player.playerId;
                            
                            return (
                              <div
                                key={player.playerId}
                                className="flex items-center justify-between p-3 rounded-lg border bg-card hover:bg-accent/50 transition-colors animate-in fade-in-0 slide-in-from-left-2"
                                style={{ animationDelay: `${index * 50}ms` }}
                              >
                                <div className="flex items-center gap-2 flex-1 min-w-0">
                                  {isEditingThisPlayer ? (
                                    <div className="flex items-center gap-2 flex-1">
                                      <Input
                                        value={editingName}
                                        onChange={(e) => setEditingName(e.target.value)}
                                        onKeyDown={(e) => {
                                          if (e.key === "Enter") {
                                            handleSavePlayerName(player.playerId);
                                          } else if (e.key === "Escape") {
                                            setEditingPlayerId(null);
                                            setEditingName("");
                                          }
                                        }}
                                        className="h-8 flex-1 text-sm"
                                        autoFocus
                                        placeholder="Player name"
                                      />
                                      <Button
                                        variant="ghost"
                                        size="icon"
                                        onClick={() => handleSavePlayerName(player.playerId)}
                                        className="h-6 w-6"
                                        disabled={!editingName.trim()}
                                      >
                                        <span className="text-xs">✓</span>
                                      </Button>
                                      <Button
                                        variant="ghost"
                                        size="icon"
                                        onClick={() => {
                                          setEditingPlayerId(null);
                                          setEditingName("");
                                        }}
                                        className="h-6 w-6"
                                      >
                                        <X className="h-3.5 w-3.5" />
                                      </Button>
                                    </div>
                                  ) : (
                                    <>
                                      <span className="font-medium">{player.name}</span>
                                      {isCurrentPlayer && (
                                        <Button
                                          variant="ghost"
                                          size="icon"
                                          onClick={() => {
                                            setEditingPlayerId(player.playerId);
                                            setEditingName(player.name);
                                          }}
                                          className="h-6 w-6 ml-1"
                                          title="Edit your name"
                                        >
                                          <Edit2 className="h-3.5 w-3.5" />
                                        </Button>
                                      )}
                                      {player.playerId === currentRoom.hostId && (
                                        <span className="flex items-center gap-1 text-xs font-semibold text-primary bg-primary/10 px-2 py-0.5 rounded-full">
                                          <Crown className="h-3 w-3" />
                                          Host
                                        </span>
                                      )}
                                    </>
                                  )}
                                </div>
                                {!isEditingThisPlayer && isHost &&
                                  player.playerId !== currentRoom.hostId && (
                                    <Button
                                      variant="ghost"
                                      size="icon"
                                      onClick={() =>
                                        handleKickPlayer(player.playerId)
                                      }
                                      className="h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                                    >
                                      <X className="h-4 w-4" />
                                    </Button>
                                  )}
                              </div>
                            );
                          })}
                        </div>
                      </div>

                      {/* Action Buttons */}
                      <div className="space-y-2 pt-4 border-t">
                        {isHost ? (
                          <Button
                            onClick={handleStartGame}
                            disabled={currentRoom.players.length < 1}
                            className="w-full h-12 text-lg font-semibold hover:scale-[1.02] active:scale-[0.98] transition-transform"
                            size="lg"
                          >
                            <Play className="h-5 w-5 mr-2" />
                            Start Game
                          </Button>
                        ) : (
                          <div className="p-3 bg-muted/50 rounded-lg text-center text-sm text-muted-foreground">
                            Waiting for host to start the game...
                          </div>
                        )}
                        <Button
                          onClick={handleLeaveRoom}
                          variant="outline"
                          className="w-full"
                          size="lg"
                        >
                          <LogOut className="h-4 w-4 mr-2" />
                          Leave Room
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-12 text-muted-foreground">
                      <User className="h-12 w-12 mx-auto mb-4 opacity-50" />
                      <p>Create or join a room to see players here</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
