import { useState } from "react";
import { useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";
import { setPlayerToken, getPlayerToken } from "../utils/storage";

interface LobbyProps {
  onRoomCreated: (roomId: string) => void;
  onRoomJoined: (roomId: string) => void;
}

export default function Lobby({ onRoomCreated, onRoomJoined }: LobbyProps) {
  const [playerName, setPlayerName] = useState("");
  const [gameCode, setGameCode] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [isJoining, setIsJoining] = useState(false);
  const [error, setError] = useState("");

  // @ts-expect-error - api.games will be generated by Convex
  const createRoom = useMutation(api.games.createRoom);
  // @ts-expect-error - api.games will be generated by Convex
  const joinRoom = useMutation(api.games.joinRoom);

  const handleCreateRoom = async () => {
    if (!playerName.trim()) {
      setError("Please enter your name");
      return;
    }

    setIsCreating(true);
    setError("");

    try {
      let token = getPlayerToken();
      if (!token) {
        // Generate a new token
        token = crypto.randomUUID();
        setPlayerToken(token);
      }

      const result = await createRoom({
        hostToken: token,
        playerName: playerName.trim(),
      });

      onRoomCreated(result.roomId);
    } catch (err: any) {
      setError(err.message || "Failed to create room");
    } finally {
      setIsCreating(false);
    }
  };

  const handleJoinRoom = async () => {
    if (!playerName.trim()) {
      setError("Please enter your name");
      return;
    }

    if (!gameCode.trim()) {
      setError("Please enter a game code");
      return;
    }

    setIsJoining(true);
    setError("");

    try {
      let token = getPlayerToken();
      if (!token) {
        token = crypto.randomUUID();
        setPlayerToken(token);
      }

      const result = await joinRoom({
        gameCode: gameCode.trim().toUpperCase(),
        playerToken: token,
        playerName: playerName.trim(),
      });

      onRoomJoined(result.roomId);
    } catch (err: any) {
      setError(err.message || "Failed to join room");
    } finally {
      setIsJoining(false);
    }
  };

  return (
    <div style={{ maxWidth: "500px", margin: "0 auto", padding: "2rem" }}>
      <h1>AI Game Lobby</h1>
      
      <div style={{ marginBottom: "2rem" }}>
        <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "bold" }}>
          Your Name
        </label>
        <input
          type="text"
          value={playerName}
          onChange={(e) => setPlayerName(e.target.value)}
          placeholder="Enter your name"
          style={{
            width: "100%",
            padding: "0.75rem",
            fontSize: "1rem",
            borderRadius: "4px",
            border: "1px solid #ccc",
          }}
          onKeyPress={(e) => {
            if (e.key === "Enter") {
              if (gameCode) handleJoinRoom();
              else handleCreateRoom();
            }
          }}
        />
      </div>

      <div style={{ marginBottom: "2rem" }}>
        <button
          onClick={handleCreateRoom}
          disabled={isCreating || isJoining}
          style={{
            width: "100%",
            padding: "1rem",
            fontSize: "1.1rem",
            fontWeight: "bold",
            backgroundColor: "#646cff",
            color: "white",
            border: "none",
            borderRadius: "4px",
            cursor: isCreating || isJoining ? "not-allowed" : "pointer",
            opacity: isCreating || isJoining ? 0.6 : 1,
          }}
        >
          {isCreating ? "Creating..." : "Create Room"}
        </button>
      </div>

      <div style={{ textAlign: "center", marginBottom: "1rem" }}>
        <span style={{ fontSize: "1.2rem" }}>OR</span>
      </div>

      <div style={{ marginBottom: "2rem" }}>
        <label style={{ display: "block", marginBottom: "0.5rem", fontWeight: "bold" }}>
          Game Code
        </label>
        <input
          type="text"
          value={gameCode}
          onChange={(e) => setGameCode(e.target.value.toUpperCase())}
          placeholder="Enter game code"
          style={{
            width: "100%",
            padding: "0.75rem",
            fontSize: "1rem",
            borderRadius: "4px",
            border: "1px solid #ccc",
            textTransform: "uppercase",
            letterSpacing: "0.1em",
          }}
          maxLength={6}
          onKeyPress={(e) => {
            if (e.key === "Enter") {
              handleJoinRoom();
            }
          }}
        />
      </div>

      <div style={{ marginBottom: "2rem" }}>
        <button
          onClick={handleJoinRoom}
          disabled={isCreating || isJoining}
          style={{
            width: "100%",
            padding: "1rem",
            fontSize: "1.1rem",
            fontWeight: "bold",
            backgroundColor: "#646cff",
            color: "white",
            border: "none",
            borderRadius: "4px",
            cursor: isCreating || isJoining ? "not-allowed" : "pointer",
            opacity: isCreating || isJoining ? 0.6 : 1,
          }}
        >
          {isJoining ? "Joining..." : "Join Room"}
        </button>
      </div>

      {error && (
        <div
          style={{
            padding: "1rem",
            backgroundColor: "#ff4444",
            color: "white",
            borderRadius: "4px",
            marginTop: "1rem",
          }}
        >
          {error}
        </div>
      )}
    </div>
  );
}

