import { useQuery, useMutation } from "convex/react";
import { api } from "../../convex/_generated/api";
import { getPlayerToken } from "../utils/storage";

interface WaitingRoomProps {
  roomId: string;
  onGameStart: () => void;
}

export default function WaitingRoom({ roomId, onGameStart }: WaitingRoomProps) {
  // @ts-expect-error - api.games will be generated by Convex
  const room = useQuery(api.games.getRoom, { roomId: roomId as any });
  // @ts-expect-error - api.games will be generated by Convex
  const startGame = useMutation(api.games.startGame);
  const playerToken = getPlayerToken();

  const isHost = room && playerToken && room.hostId === playerToken;

  const handleStartGame = async () => {
    try {
      await startGame({ roomId: roomId as any });
      onGameStart();
    } catch (err: any) {
      alert(err.message || "Failed to start game");
    }
  };

  if (!room) {
    return <div>Loading...</div>;
  }

  return (
    <div style={{ maxWidth: "600px", margin: "0 auto", padding: "2rem" }}>
      <h1>Waiting Room</h1>
      
      <div
        style={{
          backgroundColor: "var(--code-bg, #f0f0f0)",
          padding: "2rem",
          borderRadius: "8px",
          marginBottom: "2rem",
          textAlign: "center",
        }}
      >
        <div style={{ fontSize: "0.9rem", color: "var(--code-text, #666)", marginBottom: "0.5rem" }}>
          Share this code with other players:
        </div>
        <div
          style={{
            fontSize: "3rem",
            fontWeight: "bold",
            letterSpacing: "0.2em",
            color: "#646cff",
            fontFamily: "monospace",
          }}
        >
          {room.gameCode}
        </div>
      </div>

      <div style={{ marginBottom: "2rem" }}>
        <h2>Players ({room.players.length})</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
          {room.players.map((player) => (
            <div
              key={player.playerId}
              style={{
                padding: "1rem",
                backgroundColor: "var(--player-card-bg, #fff)",
                borderRadius: "4px",
                border: "1px solid var(--player-card-border, #ddd)",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <span style={{ color: "var(--player-name-color, inherit)" }}>{player.name}</span>
              {player.playerId === room.hostId && (
                <span
                  style={{
                    fontSize: "0.8rem",
                    color: "#646cff",
                    fontWeight: "bold",
                  }}
                >
                  HOST
                </span>
              )}
            </div>
          ))}
        </div>
      </div>

      {isHost && (
        <button
          onClick={handleStartGame}
          disabled={room.players.length < 1}
          style={{
            width: "100%",
            padding: "1rem",
            fontSize: "1.1rem",
            fontWeight: "bold",
            backgroundColor: room.players.length < 1 ? "#ccc" : "#646cff",
            color: "white",
            border: "none",
            borderRadius: "4px",
            cursor: room.players.length < 1 ? "not-allowed" : "pointer",
          }}
        >
          Start Game
        </button>
      )}

      {!isHost && (
        <div
          style={{
            padding: "1rem",
            backgroundColor: "var(--waiting-bg, #e8f4f8)",
            borderRadius: "4px",
            textAlign: "center",
            color: "var(--waiting-text, inherit)",
          }}
        >
          Waiting for host to start the game...
        </div>
      )}
    </div>
  );
}

