import { useState, useEffect } from 'react'
import './App.css'
import { useQuery } from "convex/react";
import { api } from "../convex/_generated/api";
import { getPlayerToken } from "./utils/storage";
import Lobby from "./components/Lobby";
import WaitingRoom from "./components/WaitingRoom";
import GameScreen from "./components/GameScreen";
import type { Id } from "../convex/_generated/dataModel";

type Screen = "lobby" | "waiting" | "game";

function App() {
  const [screen, setScreen] = useState<Screen>("lobby");
  const [roomId, setRoomId] = useState<Id<"rooms"> | "">("");

  useEffect(() => {
    // Check for player token, redirect to lobby if missing
    if (!getPlayerToken()) {
      setScreen("lobby");
      return;
    }

    // If we have a roomId stored, try to load it
    // For now, just show lobby - player will need to rejoin
    // In a production app, you'd store roomId in localStorage too
  }, []);

  const handleRoomCreated = (newRoomId: string) => {
    setRoomId(newRoomId as Id<"rooms">);
    setScreen("waiting");
  };

  const handleRoomJoined = (newRoomId: string) => {
    setRoomId(newRoomId as Id<"rooms">);
    setScreen("waiting");
  };

  const handleGameStart = () => {
    setScreen("game");
  };

  // Monitor room status to auto-advance screens
  // Note: api.games will be available after Convex generates types
  const room = useQuery(
    // @ts-expect-error - api.games will be generated by Convex
    api.games?.getRoom,
    roomId ? { roomId } : "skip"
  );

  useEffect(() => {
    if (room) {
      if (room.status === "playing" && screen === "waiting") {
        setScreen("game");
      } else if (room.status === "waiting" && screen === "game") {
        setScreen("waiting");
      }
    }
  }, [room, screen]);

  if (screen === "lobby") {
    return <Lobby onRoomCreated={handleRoomCreated} onRoomJoined={handleRoomJoined} />;
  }

  if (screen === "waiting" && roomId) {
    return <WaitingRoom roomId={roomId} onGameStart={handleGameStart} />;
  }

  if (screen === "game" && roomId) {
    return <GameScreen roomId={roomId} />;
  }

  return <div>Loading...</div>;
}

export default App
